package rivirtual;

import java.awt.AWTException;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.KeyEvent;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import io.github.bonigarcia.wdm.WebDriverManager;

public class CorporateHousingPPostingRealtor {

	public static void main(String[] args) throws InterruptedException, AWTException {
		// TODO Auto-generated method stub
		WebDriverManager.chromedriver().setup();
		WebDriver driver = new ChromeDriver();
		driver.get("https://rivirtual.net/preview/");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[@class='opening-close']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//*[normalize-space(text())='Sign In']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@value='realtoravttyp']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//a[text()=\"Continue\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.name("agentusername")).sendKeys("ramya1002@rivirtuals.com");
		Thread.sleep(2000);
		driver.findElement(By.name("agentloginpassword")).sendKeys("ramya1002@rivirtuals.com");
		Thread.sleep(2000);
		driver.findElement(By.id("agentloginbtn")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//*[normalize-space(.)='Manage Properties']")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//a[normalize-space(.)='Add Property'])[2]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//label[@class=\"radio\"])[1]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//label[@class=\"radio\"])[13]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//label[@class=\"radio\"])[22]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//input[@placeholder=\"Enter property name..\"]")).sendKeys("Rajeshwari test Corporate Housing");
		Thread.sleep(2000);
		driver.findElement(By.id("no_of_bedrooms")).sendKeys("2");
		Thread.sleep(2000);
		driver.findElement(By.id("bathroom")).sendKeys("2");
		Thread.sleep(2000);
		driver.findElement(By.id("floor")).sendKeys("2");
		Thread.sleep(2000);
		driver.findElement(By.id("area")).sendKeys("102");
		Thread.sleep(2000);
		driver.findElement(By.id("super_area")).sendKeys("112");
		Thread.sleep(2000);
		driver.findElement(By.id("carpet_area")).sendKeys("102");
		Thread.sleep(2000);
		driver.findElement(By.id("facing")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value=\"SF\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//label[@class=\"radio\"])[42]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//label[@class=\"radio\"])[45]")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("min_stay_du")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value=\"1W\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("rate23")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[7]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[8]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[9]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[10]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[11]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[12]")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("monthly_tariff")).sendKeys("15000");
		Thread.sleep(2000);
		driver.findElement(By.id("weekly_tariff")).sendKeys("10000");
		Thread.sleep(2000);
		driver.findElement(By.id("daily_tariff")).sendKeys("5000");
		Thread.sleep(2000);
		driver.findElement(By.id("security_deposit")).sendKeys("1000");
		Thread.sleep(2000);
		driver.findElement(By.id("adv_pay_term")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value=\"1A\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("wifi_spd")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value=\"300\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("pwr_bckp")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value=\"FG\"]")).click();
		Thread.sleep(2000);
		
		driver.findElement(By.xpath("(//label[@class=\"radio\"])[47]")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("house_keeping")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value=\"D\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("breakfast")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value=\"IN\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//label[@class=\"radio\"])[50]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//label[@class=\"radio\"])[52]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//label[@class=\"radio\"])[54]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//label[@class=\"radio\"])[57]")).click();
		Thread.sleep(2000);
		//driver.findElement(By.xpath("(//label[@class=\"radio\"])[44]")).click();
		//Thread.sleep(2000);
		driver.findElement(By.id("states")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value=\"4122\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("city")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value=\"59\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.id("city")).sendKeys("Andhra Pradesh");
		Thread.sleep(2000);
		driver.findElement(By.id("locality")).sendKeys("Ananthapur");
		Thread.sleep(2000);
		driver.findElement(By.id("address")).sendKeys("Andhra Pradesh,Ananthapur");
		Thread.sleep(2000);
		driver.findElement(By.id("post_code")).sendKeys("454545");
		Thread.sleep(2000);
		driver.findElement(By.xpath("//select[@id=\"build_year\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//option[@value=\"2023\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//textarea[@name=\"description\"]")).sendKeys("RiVirtual is a privately owned global real estate FinTech company with a presence in 100 cities in 5 countries and more than 100 million square feet of managed assets for which RiVirtual provides third-party property-level and lending services.");
		Thread.sleep(2000);
		driver.findElement(By.id("submitButton")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//div[@class=\"radiobx\"]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[2]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[3]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[4]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[5]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@class=\"radiobx\"])[6]")).click();
		Thread.sleep(2000);
		
		driver.findElement(By.xpath("//label[@for=\"file-1\"]")).click();
		Thread.sleep(2000);
		StringSelection str= new StringSelection("\"C:\\Users\\Dell\\OneDrive\\Pictures\\home 2.jpg\"");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str,null);
		Thread.sleep(2000);
		Robot r=new Robot();
		
		r.keyPress(KeyEvent.VK_CONTROL);
		r.keyPress(KeyEvent.VK_V);
		r.keyRelease(KeyEvent.VK_CONTROL);
		r.keyRelease(KeyEvent.VK_V);
		Thread.sleep(2000);
		r.keyPress(KeyEvent.VK_ENTER);
		r.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(5000);
		
		driver.findElement(By.xpath("//label[@for=\"file-2\"]")).click();
		Thread.sleep(2000);
		StringSelection str1=new StringSelection("\"C:\\Users\\Dell\\OneDrive\\Pictures\\Aaryan Aranyam.png\"");
		Toolkit.getDefaultToolkit().getSystemClipboard().setContents(str1,null);
		Thread.sleep(2000);
		Robot r1=new Robot();
		
		r1.keyPress(KeyEvent.VK_CONTROL);
		r1.keyPress(KeyEvent.VK_V);
		r1.keyRelease(KeyEvent.VK_CONTROL);
		r1.keyRelease(KeyEvent.VK_V);
		Thread.sleep(2000);
		r1.keyPress(KeyEvent.VK_ENTER);
		r1.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(5000);
		
		//driver.findElement(By.id("submitButton")).click();
		//Thread.sleep(2000);	
		
	}

}
